### ISSUE TITLE
When i clicked on some hero, then loaded blank page. 

### ISSUE THREAD

**Issue by olsanvit** [jawslouis/Battlegrounds-Stats-React#1]
When i want to watch a hero detail. 
For example:http://bgstats.cintrest.com/VitekCZ-2164/hero/Fungalmancer%20Flurgl.

I have some extra questions, that i want to talk with you via email. Please write me a email to: olsanskyvitek@gmail.com

**Comment by jawslouis** [comment]
Hey thanks for highlighting this. I've fixed it. Have also emailed you!
